export const HOT_KEYWORD_WINDOW_HOURS = 24;
export const NEW_KEYWORD_WINDOW_HOURS = 72;
export const NEW_KEYWORD_MAX_AGE_MS = NEW_KEYWORD_WINDOW_HOURS * 60 * 60 * 1000;

export const BASELINE_MAX_BEFORE_WINDOW = 5;
export const MIN_SPIKE_VALUE = 20;
export const RISING_QUEUE_THRESHOLD = 50;
export const BREAKOUT_SENTINEL_VALUE = 1000;

export const SPIKE_DECAY_WINDOW_HOURS = 24;
export const SPIKE_DECAY_MAX_VALUE = 0;

export const NEWS_KEYWORD_WINDOW_HOURS = 48;
export const NEWS_KEYWORD_MAX_SEEDS = 20;
